# Generated by Django 3.0.6 on 2020-05-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('topic', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('style', models.IntegerField(choices=[(1, 'POWOLUTKU'), (2, 'KRAJOZNAWCZO'), (3, 'NIECO MOCNIEJ'), (4, 'OGIEN')])),
                ('distans', models.IntegerField()),
                ('city_start', models.CharField(max_length=20)),
                ('data_start', models.DateTimeField()),
            ],
        ),
    ]
