# Generated by Django 3.0.6 on 2020-05-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mf', '0002_auto_20200504_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='city_start',
            field=models.CharField(max_length=20, verbose_name='miasto startu'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='content',
            field=models.TextField(verbose_name='opis wyjazdu'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='data_start',
            field=models.DateField(verbose_name='data startu (RRRR-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distans',
            field=models.IntegerField(verbose_name='planowany dystans w obie strony'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='style',
            field=models.IntegerField(choices=[(1, 'POWOLUTKU'), (2, 'KRAJOZNAWCZO'), (3, 'NIECO MOCNIEJ'), (4, 'OGIEN')], verbose_name='styl jazdy'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='topic',
            field=models.CharField(max_length=50, verbose_name='tytuł'),
        ),
    ]
