# Generated by Django 3.0.6 on 2020-05-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mf', '0003_auto_20200505_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='co tam sie nie dzialo?')),
                ('topic', models.CharField(max_length=50, verbose_name='gdzie bylismy')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('style', models.IntegerField(choices=[(1, 'POWOLUTKU'), (2, 'KRAJOZNAWCZO'), (3, 'NIECO MOCNIEJ'), (4, 'OGIEN')], verbose_name='styl jazdy')),
                ('distans', models.IntegerField(verbose_name='planowany dystans w obie strony')),
                ('city_start', models.CharField(max_length=20, verbose_name='miasto startu')),
                ('data_start', models.DateField(verbose_name='data startu (RRRR-MM-DD)')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='opis wyjazdu')),
                ('topic', models.CharField(max_length=50, verbose_name='tytuł')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('subject', models.IntegerField(choices=[(1, 'MOTOCYKLE'), (2, 'KASKI'), (3, 'KURTKI'), (4, 'SPODNIE'), (5, 'BUTY'), (6, 'MIEJSCA'), (7, 'INNE')], verbose_name='czego dotyczy')),
                ('price', models.IntegerField(verbose_name='ile to kosztuje')),
            ],
        ),
    ]
