# Generated by Django 3.0.6 on 2020-05-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mf', '0004_relation_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reviews',
            name='content',
            field=models.TextField(verbose_name='co to za produkt'),
        ),
    ]
