# Generated by Django 3.0.6 on 2020-05-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mf', '0008_commenttrip_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenttrips', to='mf.Trip'),
        ),
    ]
