# Generated by Django 3.0.6 on 2020-05-07 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mf', '0009_auto_20200507_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mf.Trip'),
        ),
    ]
