# Generated by Django 3.0.6 on 2020-05-07 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mf', '0010_auto_20200507_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttrip',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_ser', to=settings.AUTH_USER_MODEL),
        ),
    ]
