# Generated by Django 3.0.6 on 2020-05-05 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40, verbose_name='skąd ruszasz?')),
                ('age', models.IntegerField(verbose_name='Twój wiek?')),
                ('bike_type', models.IntegerField(choices=[(1, 'Chopper/cruiser'), (2, 'Cross/Enduro'), (3, 'ATV'), (4, 'Szosa/turystyk')], verbose_name='typ motocykla')),
                ('about', models.TextField(verbose_name='Powiedz coś o sobie!')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
