# Generated by Django 3.0.6 on 2020-05-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.IntegerField(choices=[(1, 'DOLNOŚLĄSKIE'), (2, 'KUJAWSKO-POMORSKIE'), (3, 'LUBELSKIE'), (4, 'LUBUSKIE'), (5, 'ŁÓDZKIE'), (6, 'MAŁOPOLSKIE'), (7, 'MAZOWIECKIE'), (8, 'OPOLSKIE'), (9, 'PODKARPACKIE'), (10, 'PODLASKIE'), (11, 'POMORSKIE'), (12, 'ŚLĄSKIE'), (13, 'ŚWIĘTOKRZYSKIE'), (14, 'WARMIŃSKO-MAZURSKIE'), (15, 'WIELKOPOLSKIE'), (16, 'ZACHODNIOPOMORSKIE')], verbose_name='skąd ruszasz?'),
        ),
    ]
